/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as StudentWishlistRouteImport } from './routes/student/wishlist'
import { Route as StudentQuizzesRouteImport } from './routes/student/quizzes'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as InstructorStudentsRouteImport } from './routes/instructor/students'
import { Route as InstructorProfileRouteImport } from './routes/instructor/profile'
import { Route as InstructorEarningsRouteImport } from './routes/instructor/earnings'
import { Route as InstructorCoursesRouteImport } from './routes/instructor/courses'
import { Route as InstructorContentRouteImport } from './routes/instructor/content'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor/analytics'
import { Route as CourseCourseIdRouteImport } from './routes/course/$courseId'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWishlistRoute = StudentWishlistRouteImport.update({
  id: '/student/wishlist',
  path: '/student/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuizzesRoute = StudentQuizzesRouteImport.update({
  id: '/student/quizzes',
  path: '/student/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorStudentsRoute = InstructorStudentsRouteImport.update({
  id: '/instructor/students',
  path: '/instructor/students',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorProfileRoute = InstructorProfileRouteImport.update({
  id: '/instructor/profile',
  path: '/instructor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorEarningsRoute = InstructorEarningsRouteImport.update({
  id: '/instructor/earnings',
  path: '/instructor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCoursesRoute = InstructorCoursesRouteImport.update({
  id: '/instructor/courses',
  path: '/instructor/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorContentRoute = InstructorContentRouteImport.update({
  id: '/instructor/content',
  path: '/instructor/content',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/instructor/analytics',
  path: '/instructor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/content': typeof InstructorContentRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/instructor/': typeof InstructorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/content': typeof InstructorContentRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/instructor': typeof InstructorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/content': typeof InstructorContentRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/instructor/': typeof InstructorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/course/$courseId'
    | '/instructor/analytics'
    | '/instructor/content'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/profile'
    | '/instructor/students'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/wishlist'
    | '/instructor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/course/$courseId'
    | '/instructor/analytics'
    | '/instructor/content'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/profile'
    | '/instructor/students'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/wishlist'
    | '/instructor'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/course/$courseId'
    | '/instructor/analytics'
    | '/instructor/content'
    | '/instructor/courses'
    | '/instructor/earnings'
    | '/instructor/profile'
    | '/instructor/students'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/wishlist'
    | '/instructor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorContentRoute: typeof InstructorContentRoute
  InstructorCoursesRoute: typeof InstructorCoursesRoute
  InstructorEarningsRoute: typeof InstructorEarningsRoute
  InstructorProfileRoute: typeof InstructorProfileRoute
  InstructorStudentsRoute: typeof InstructorStudentsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentQuizzesRoute: typeof StudentQuizzesRoute
  StudentWishlistRoute: typeof StudentWishlistRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/wishlist': {
      id: '/student/wishlist'
      path: '/student/wishlist'
      fullPath: '/student/wishlist'
      preLoaderRoute: typeof StudentWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/quizzes': {
      id: '/student/quizzes'
      path: '/student/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof StudentQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/students': {
      id: '/instructor/students'
      path: '/instructor/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/profile': {
      id: '/instructor/profile'
      path: '/instructor/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/earnings': {
      id: '/instructor/earnings'
      path: '/instructor/earnings'
      fullPath: '/instructor/earnings'
      preLoaderRoute: typeof InstructorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses': {
      id: '/instructor/courses'
      path: '/instructor/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/content': {
      id: '/instructor/content'
      path: '/instructor/content'
      fullPath: '/instructor/content'
      preLoaderRoute: typeof InstructorContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorContentRoute: InstructorContentRoute,
  InstructorCoursesRoute: InstructorCoursesRoute,
  InstructorEarningsRoute: InstructorEarningsRoute,
  InstructorProfileRoute: InstructorProfileRoute,
  InstructorStudentsRoute: InstructorStudentsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentQuizzesRoute: StudentQuizzesRoute,
  StudentWishlistRoute: StudentWishlistRoute,
  InstructorIndexRoute: InstructorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
